[project]
name = 'Circular-Economy-Tracking-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.product-lifecycle]
path = 'contracts/product-lifecycle.clar'
clarity_version = 2
epoch = 2.5

[contracts.recycling-incentives]
path = 'contracts/recycling-incentives.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
